=== thailyn/Procurement/POEApi.Model/Data.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Data"
    targetNamespace="http://tempuri.org/Data.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/Data.xsd"
    xmlns:mstns="http://tempuri.org/Data.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="Data">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="GearBaseTypes" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Item">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:string" />
      <xs:attribute name="value" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== thailyn/Procurement/POEApi.Model/Data.xml
<?xml version="1.0" encoding="utf-8" ?>
<Data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Data.xsd">
  <GearBaseTypes>
    <GearBaseType name="Ring">
      <Item value="Iron Ring"/>
      <Item value="Coral Ring"/>
      <Item value="Paua Ring"/>
      <Item value="Gold Ring"/>
      <Item value="Ruby Ring"/>
      <Item value="Sapphire Ring"/>
      <Item value="Topaz Ring"/>
      <Item value="Diamond Ring"/>
      <Item value="Moonstone Ring"/>
      <Item value="Prismatic Ring"/>
      <Item value="Amethyst Ring"/>
      <Item value="Two-Stone Ring"/>
    </GearBaseType>
    <GearBaseType name="Amulet">
      <Item value="Paua Amulet"/>
      <Item value="Coral Amulet"/>
      <Item value="Amber Amulet"/>
      <Item value="Jade Amulet"/>
      <Item value="Lapis Amulet"/>
      <Item value="Gold Amulet"/>
      <Item value="Onyx Amulet"/>
      <Item value="Agate Amulet"/>
      <Item value="Turquoise Amulet"/>
      <Item value="Citrine Amulet"/>
    </GearBaseType>
    <GearBaseType name="Helmet">
      <Item value="Iron Hat"/>
      <Item value="Cone Helmet"/>
      <Item value="Barbute Helmet"/>
      <Item value="Close Helmet"/>
      <Item value="Gladiator Helmet"/>
      <Item value="Reaver Helmet"/>
      <Item value="Siege Helmet"/>
      <Item value="Samnite Helmet"/>
      <Item value="Ezomyte Burgonet"/>
      <Item value="Royal Burgonet"/>
      <Item value="Eternal Burgonet"/>
      
      <Item value="Leather Cap"/>
      <Item value="Tricorne"/>
      <Item value="Leather Hood"/>
      <Item value="Wolf Pelt"/>
      <Item value="Hunter Hood"/>
      <Item value="Noble Tricorne"/>
      <Item value="Ursine Pelt"/>
      <Item value="Silken Hood"/>
      <Item value="Sinner Tricorne"/>
      <Item value="Lion Pelt"/>
      
      <Item value="Vine Circlet"/>
      <Item value="Iron Circlet"/>
      <Item value="Torture Cage"/>
      <Item value="Tribal Circlet"/>
      <Item value="Bone Circlet"/>
      <Item value="Lunaris Circlet"/>
      <Item value="Steel Circlet"/>
      <Item value="Necromancer Circlet"/>
      <Item value="Solaris Circlet"/>
      <Item value="Mind Cage"/>
      <Item value="Hubris Circlet"/>
      
      <Item value="Battered Helm"/>
      <Item value="Visored Sallet"/>
      <Item value="Gilded Sallet"/>
      <Item value="Secutor Helm"/>
      <Item value="Fencer Helm"/>
      <Item value="Lacquered Helmet"/>
      <Item value="Fluted Bascinet"/>
      <Item value="Pig Faced Bascinet"/>
      <Item value="Nightmare Bascinet"/>
      <Item value="Sallet"/>

      <Item value="Rusted Coif"/>
      <Item value="Soldier Helmet"/>
      <Item value="Great Helmet"/>
      <Item value="Crusader Helmet"/>
      <Item value="Aventail Helmet"/>
      <Item value="Zealot Helmet"/>
      <Item value="Great Crown"/>
      <Item value="Magistrate Crown"/>
      <Item value="Prophet Crown"/>
      <Item value="Praetor Crown"/>
      
      <Item value="Scare Mask"/>
      <Item value="Plague Mask"/>
      <Item value="Iron Mask"/>
      <Item value="Festival Mask"/>
      <Item value="Golden Mask"/>
      <Item value="Raven Mask"/>
      <Item value="Callous Mask"/>
      <Item value="Regicide Mask"/>
      <Item value="Harlequin Mask"/>
      <Item value="Vaal Mask"/>
      <Item value="Deicide Mask"/>
    </GearBaseType>
    <GearBaseType name="Chest">
      <Item value="Plate Vest"/>
      <Item value="Chestplate"/>
      <Item value="Copper Plate"/>
      <Item value="War Plate"/>
      <Item value="Full Plate"/>
      <Item value="Arena Plate"/>
      <Item value="Lordly Plate"/>
      <Item value="Bronze Plate"/>
      <Item value="Battle Plate"/>
      <Item value="Sun Plate"/>
      <Item value="Colosseum Plate"/>
      <Item value="Majestic Plate"/>
      <Item value="Golden Plate"/>
      <Item value="Crusader Plate"/>
      <Item value="Astral Plate"/>
      <Item value="Gladiator Plate"/>
      <Item value="Glorious Plate"/>

      <Item value="Shabby Jerkin"/>
      <Item value="Strapped Leather"/>
      <Item value="Buckskin Tunic"/>
      <Item value="Wild Leather"/>
      <Item value="Full Leather"/>
      <Item value="Sun Leather"/>
      <Item value="Thief's Garb"/>
      <Item value="Eelskin Tunic"/>
      <Item value="Frontier Leather"/>
      <Item value="Glorious Leather"/>
      <Item value="Coronal Leather"/>
      <Item value="Cutthroat's Garb"/>
      <Item value="Sharkskin Tunic"/>
      <Item value="Destiny Leather"/>
      <Item value="Exquisite Leather"/>
      <Item value="Zodiac Leather"/>
      <Item value="Assassin's Garb"/>

      <Item value="Simple Robe"/>
      <Item value="Silken Vest"/>
      <Item value="Scholar's Robe"/>
      <Item value="Silken Garb"/>
      <Item value="Mage's Vestment"/>
      <Item value="Silk Robe"/>
      <Item value="Cabalist Regalia"/>
      <Item value="Sage's Robe"/>
      <Item value="Silken Wrap"/>
      <Item value="Conjurer's Vestment"/>
      <Item value="Spidersilk Robe"/>
      <Item value="Destroyer Regalia"/>
      <Item value="Savant's Robe"/>
      <Item value="Necromancer Silks"/>
      <Item value="Occultist's Vestment"/>
      <Item value="Widowsilk Robe"/>
      <Item value="Vaal Regalia"/>

      <Item value="Scale Vest"/>
      <Item value="Light Brigandine"/>
      <Item value="Scale Doublet"/>
      <Item value="Infantry Brigandine"/>
      <Item value="Full Scale Armour"/>
      <Item value="Soldier's Brigandine"/>
      <Item value="Field Lamellar"/>
      <Item value="Wyrmscale Doublet"/>
      <Item value="Hussar Brigandine"/>
      <Item value="Full Wyrmscale"/>
      <Item value="Commander's Brigandine"/>
      <Item value="Battle Lamellar"/>
      <Item value="Dragonscale Doublet"/>
      <Item value="Desert Brigandine"/>
      <Item value="Full Dragonscale"/>
      <Item value="General's Brigandine"/>
      <Item value="Triumphant Lamellar"/>

      <Item value="Chainmail Vest"/>
      <Item value="Chainmail Tunic"/>
      <Item value="Ringmail Coat"/>
      <Item value="Chainmail Doublet"/>
      <Item value="Full Ringmail"/>
      <Item value="Full Chainmail"/>
      <Item value="Holy Chainmail"/>
      <Item value="Latticed Ringmail"/>
      <Item value="Crusader Chainmail"/>
      <Item value="Ornate Ringmail"/>
      <Item value="Chain Hauberk"/>
      <Item value="Devout Chainmail"/>
      <Item value="Loricated Ringmail"/>
      <Item value="Conquest Chainmail"/>
      <Item value="Elegant Ringmail"/>
      <Item value="Saint's Hauberk"/>
      <Item value="Saintly Chainmail"/>

      <Item value="Padded Vest"/>
      <Item value="Oiled Vest"/>
      <Item value="Padded Jacket"/>
      <Item value="Oiled Coat"/>
      <Item value="Scarlet Raiment"/>
      <Item value="Waxed Garb"/>
      <Item value="Bone Armour"/>
      <Item value="Quilted Jacket"/>
      <Item value="Sleek Coat"/>
      <Item value="Crimson Raiment"/>
      <Item value="Lacquered Garb"/>
      <Item value="Crypt Armour"/>
      <Item value="Sentinel Jacket"/>
      <Item value="Varnished Coat"/>
      <Item value="Blood Raiment"/>
      <Item value="Sadist Garb"/>
      <Item value="Carnal Armour"/>
    </GearBaseType>
    <GearBaseType name="Belt">
      <Item value="Rustic Sash"/>
      <Item value="Chain Belt"/>
      <Item value="Leather Belt"/>
      <Item value="Heavy Belt"/>
      <Item value="Studded Belt"/>
      <Item value="Cloth Belt"/>
    </GearBaseType>
    <GearBaseType name="Flask">
      <Item value="Small Life Flask"/>
      <Item value="Medium Life Flask"/>
      <Item value="Large Life Flask"/>
      <Item value="Greater Life Flask"/>
      <Item value="Grand Life Flask"/>
      <Item value="Giant Life Flask"/>
      <Item value="Colossal Life Flask"/>
      <Item value="Sacred Life Flask"/>
      <Item value="Hallowed Life Flask"/>
      <Item value="Sanctified Life Flask"/>

      <Item value="Small Mana Flask"/>
      <Item value="Medium Mana Flask"/>
      <Item value="Large Mana Flask"/>
      <Item value="Greater Mana Flask"/>
      <Item value="Grand Mana Flask"/>
      <Item value="Giant Mana Flask"/>
      <Item value="Colossal Mana Flask"/>
      <Item value="Sacred Mana Flask"/>
      <Item value="Hallowed Mana Flask"/>
      <Item value="Sanctified Mana Flask"/>

      <Item value="Small Hybrid Flask"/>
      <Item value="Medium Hybrid Flask"/>
      <Item value="Large Hybrid Flask"/>
      <Item value="Colossal Hybrid Flask"/>
      <Item value="Sacred Hybrid Flask"/>
      <Item value="Hallowed Hybrid Flask"/>

      <Item value="Quicksilver Flask"/>
      <Item value="Ruby Flask"/>
      <Item value="Sapphire Flask"/>
      <Item value="Topaz Flask"/>
      <Item value="Amethyst Flask"/>
      <Item value="Granite Flask"/>
      <Item value="Diamond Flask"/>
      <Item value="Jade Flask"/>
      <Item value="Quartz Flask"/>
    </GearBaseType>
    <GearBaseType name="Map">
      <Item value="Crypt Map"/>
      <Item value="Dried Lake Map"/>
      <Item value="Dunes Map"/>
      <Item value="Dungeon Map"/>
      <Item value="Grotto Map"/>
      <Item value="Orchard Map"/>
      <Item value="Overgrown Ruin Map"/>
      <Item value="Tropical Island Map"/>

      <Item value="Arcade Map"/>
      <Item value="Arsenal Map"/>
      <Item value="Cemetery Map"/>
      <Item value="Mountain Ledge Map"/>
      <Item value="Sewer Map"/>
      <Item value="Thicket Map"/>
      <Item value="Wharf Map"/>

      <Item value="Ghetto Map"/>
      <Item value="Mud Geyser Map"/>
      <Item value="Museum Map"/>
      <Item value="Reef Map"/>
      <Item value="Spider Lair Map"/>
      <Item value="Springs Map"/>
      <Item value="Vaal Pyramid Map"/>

      <Item value="Catacomb Map"/>
      <Item value="Overgrown Shrine Map"/>
      <Item value="Promenade Map"/>
      <Item value="Shore Map"/>
      <Item value="Spider Forest Map"/>
      <Item value="Tunnel Map"/>

      <Item value="Bog Map"/>
      <Item value="Coves Map"/>
